# Generated by Django 4.1.7 on 2023-02-25 13:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=80)),
                ('route_dir', models.CharField(max_length=80)),
                ('route_shor', models.CharField(max_length=80)),
                ('route_long', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=2263)),
            ],
        ),
    ]
