# Generated by Django 4.1.7 on 2023-04-30 01:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_id", models.CharField(max_length=80)),
                ("route_dir", models.CharField(max_length=80)),
                ("route_shor", models.CharField(max_length=80)),
                ("route_long", models.CharField(max_length=80)),
                ("color", models.CharField(max_length=80)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusRouteExpress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_id", models.CharField(max_length=80)),
                ("route_dir", models.CharField(max_length=80)),
                ("route_shor", models.CharField(max_length=80)),
                ("route_long", models.CharField(max_length=80)),
                ("color", models.CharField(max_length=80)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_id", models.IntegerField()),
                ("stop_name", models.CharField(max_length=80)),
                ("stop_lat", models.FloatField()),
                ("stop_lon", models.FloatField()),
                ("geoid", models.CharField(max_length=80)),
                ("namelsad", models.CharField(max_length=80)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="BusStopExpress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_id", models.IntegerField()),
                ("stop_name", models.CharField(max_length=80)),
                ("stop_lat", models.FloatField()),
                ("stop_lon", models.FloatField()),
                ("geoid", models.CharField(max_length=80)),
                ("namelsad", models.CharField(max_length=80)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility_type", models.CharField(max_length=80)),
                ("facility_name", models.CharField(max_length=80)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="Park",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acres", models.CharField(max_length=80)),
                ("location", models.CharField(max_length=100)),
                ("signname", models.CharField(max_length=80)),
                ("typecategory", models.CharField(max_length=80)),
                ("waterfront", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_code", models.CharField(max_length=80)),
                ("location_code", models.CharField(max_length=80)),
                ("location_name", models.CharField(max_length=80)),
                ("managed_by_name", models.CharField(max_length=80)),
                ("location_type_description", models.CharField(max_length=80)),
                ("location_category_description", models.CharField(max_length=80)),
                ("status_descriptions", models.CharField(max_length=80)),
                ("primary_address_line_1", models.CharField(max_length=80)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="SubwayRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_id", models.CharField(max_length=80)),
                ("route_shor", models.CharField(max_length=80)),
                ("route_long", models.CharField(max_length=80)),
                ("color", models.CharField(max_length=80)),
                ("group", models.CharField(max_length=80)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubwayStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("lines", models.CharField(max_length=80)),
                ("complex_id", models.CharField(max_length=80)),
                ("gtfs_stop_id", models.CharField(max_length=80)),
                ("ada_status_code", models.IntegerField()),
                ("ridership", models.FloatField(blank=True, null=True)),
                (
                    "ada_neighbor_gap",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "betweenness_centrality",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="SubwayStation500mBuffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("line", models.CharField(max_length=80)),
                ("complex_id", models.CharField(max_length=80)),
                ("gtfs_stop_id", models.CharField(max_length=80)),
                ("ada_status_code", models.IntegerField()),
                ("schools", models.IntegerField()),
                ("parks", models.IntegerField()),
                ("hospitals", models.IntegerField()),
                ("bus_stops", models.IntegerField()),
                ("bus_stops_express", models.IntegerField()),
                ("total", models.IntegerField()),
                ("under_five", models.IntegerField()),
                ("sixty_five_and_over", models.IntegerField()),
                ("poverty_total", models.IntegerField()),
                ("poverty_under_five", models.IntegerField()),
                ("poverty_sixty_five_and_over", models.IntegerField()),
                ("under_eighteen_ambulatory", models.IntegerField()),
                ("over_eighteen_under_sixty_five_ambulatory", models.IntegerField()),
                ("sixty_five_and_over_ambulatory", models.IntegerField()),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="TractDemographic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geoid", models.CharField(max_length=80)),
                ("total", models.IntegerField()),
                ("under_five", models.IntegerField()),
                ("sixty_five_and_over", models.IntegerField()),
                ("poverty_total", models.IntegerField()),
                ("poverty_under_five", models.IntegerField()),
                ("poverty_sixty_five_and_over", models.IntegerField()),
                ("under_eighteen_ambulatory", models.IntegerField()),
                ("over_eighteen_under_sixty_five_ambulatory", models.IntegerField()),
                ("sixty_five_and_over_ambulatory", models.IntegerField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
    ]
