# Generated by Django 4.1.7 on 2023-02-25 13:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ada_stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroutes',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=2263),
        ),
    ]
