# Generated by Django 4.1.7 on 2023-03-11 17:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ada_stations', '0004_busrouteexpress'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_code', models.CharField(max_length=80)),
                ('location_code', models.CharField(max_length=80)),
                ('location_name', models.CharField(max_length=80)),
                ('managed_by_name', models.CharField(max_length=80)),
                ('location_type_description', models.CharField(max_length=80)),
                ('location_category_description', models.CharField(max_length=80)),
                ('status_descriptions', models.CharField(max_length=80)),
                ('primary_address_line_1', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
