# Generated by Django 4.1.7 on 2023-03-11 20:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ada_stations", "0005_school"),
    ]

    operations = [
        migrations.CreateModel(
            name="Park",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acres", models.CharField(max_length=80)),
                ("location", models.CharField(max_length=100)),
                ("signname", models.CharField(max_length=80)),
                ("typecategory", models.CharField(max_length=80)),
                ("waterfront", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
    ]
