# Generated by Django 4.1.7 on 2023-03-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ada_stations", "0006_park"),
    ]

    operations = [
        migrations.AlterField(
            model_name="park",
            name="location",
            field=models.CharField(max_length=100),
        ),
    ]
