# Generated by Django 4.1.7 on 2023-03-11 22:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ada_stations", "0007_hospital"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubwayRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_id", models.CharField(max_length=80)),
                ("route_shor", models.CharField(max_length=80)),
                ("route_long", models.CharField(max_length=80)),
                ("color", models.CharField(max_length=80)),
                ("group", models.CharField(max_length=80)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
                ),
            ],
        ),
    ]
