# Generated by Django 4.1.7 on 2023-03-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ada_stations", "0007_alter_park_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="park",
            name="waterfront",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
