# Generated by Django 4.1.7 on 2023-03-12 03:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ada_stations", "0008_subwayroute"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubwayStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complex_id", models.CharField(max_length=80)),
                ("complex_nm", models.CharField(max_length=80)),
                ("trains", models.CharField(max_length=80)),
                ("station_ct", models.CharField(max_length=80)),
                ("tot2019", models.CharField(max_length=80)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
