# Generated by Django 4.1.7 on 2023-03-12 04:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ada_stations", "0009_subwaystation"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubwayEntrance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line", models.CharField(max_length=254)),
                ("station_name", models.CharField(max_length=254)),
                ("route_1", models.CharField(blank=True, max_length=254, null=True)),
                ("route_2", models.CharField(blank=True, max_length=254, null=True)),
                ("route_3", models.CharField(blank=True, max_length=254, null=True)),
                ("route_4", models.CharField(blank=True, max_length=254, null=True)),
                ("route_5", models.CharField(blank=True, max_length=254, null=True)),
                ("route_6", models.CharField(blank=True, max_length=254, null=True)),
                ("route_7", models.CharField(blank=True, max_length=254, null=True)),
                ("route_8", models.BigIntegerField(blank=True, null=True)),
                ("route_9", models.BigIntegerField(blank=True, null=True)),
                ("route_10", models.BigIntegerField(blank=True, null=True)),
                ("route_11", models.BigIntegerField(blank=True, null=True)),
                ("entrance_type", models.CharField(max_length=254)),
                ("entry", models.CharField(max_length=254)),
                ("exit_only", models.CharField(blank=True, max_length=254, null=True)),
                ("ada", models.CharField(max_length=254)),
                ("ada_notes", models.CharField(blank=True, max_length=254, null=True)),
                ("free_cross", models.CharField(blank=True, max_length=254, null=True)),
                ("corner", models.CharField(blank=True, max_length=254, null=True)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
