# Generated by Django 4.1.7 on 2023-03-19 23:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ada_stations", "0010_subwayentrance"),
    ]

    operations = [
        migrations.CreateModel(
            name="TractDemographic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geoid", models.CharField(max_length=80)),
                ("total", models.IntegerField()),
                ("under_five", models.IntegerField()),
                ("sixty_five_and_over", models.IntegerField()),
                ("poverty_total", models.IntegerField()),
                ("poverty_under_five", models.IntegerField()),
                ("poverty_sixty_five_and_over", models.IntegerField()),
                ("under_eighteen_ambulatory", models.IntegerField()),
                ("over_eighteen_under_sixty_five_ambulatory", models.IntegerField()),
                ("sixty_five_and_over_ambulatory", models.IntegerField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
    ]
