# Generated by Django 4.1.7 on 2023-04-07 02:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ada_stations", "0011_tractdemographic"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubwayStationADA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("lines", models.CharField(max_length=80)),
                ("complex_id", models.CharField(max_length=80)),
                ("gtfs_stop_id", models.CharField(max_length=80)),
                ("ada_status_code", models.IntegerField()),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
