# Generated by Django 4.1.7 on 2023-04-15 12:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ada_stations", "0012_subwaystationada"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubwayStation500mBuffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("line", models.CharField(max_length=80)),
                ("complex_id", models.CharField(max_length=80)),
                ("gtfs_stop_id", models.CharField(max_length=80)),
                ("ada_status_code", models.IntegerField()),
                ("schools", models.IntegerField()),
                ("parks", models.IntegerField()),
                ("hospitals", models.IntegerField()),
                ("bus_stops", models.IntegerField()),
                ("bus_stops_express", models.IntegerField()),
                ("total", models.IntegerField()),
                ("under_five", models.IntegerField()),
                ("sixty_five_and_over", models.IntegerField()),
                ("poverty_total", models.IntegerField()),
                ("poverty_under_five", models.IntegerField()),
                ("poverty_sixty_five_and_over", models.IntegerField()),
                ("under_eighteen_ambulatory", models.IntegerField()),
                ("over_eighteen_under_sixty_five_ambulatory", models.IntegerField()),
                ("sixty_five_and_over_ambulatory", models.IntegerField()),
                ("ridership_2019", models.FloatField(blank=True, null=True)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
